(()=>{
'use strict';
const D=window.COURSE_DATA,$=s=>document.querySelector(s);
const storeKey='englishJourneyCompleteV2';
let state=JSON.parse(localStorage.getItem(storeKey)||'{"completed":{},"answers":{},"exams":{},"xp":0}');
let activeLevel='ALL',currentUnit=null,pages=[],pageIndex=0,soundOn=true;
const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function speak(t){if(!soundOn||!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}
function shuffledQuestion(q,seed=0){const rows=q.options.map((o,i)=>({o,ok:i===q.answer}));for(let i=rows.length-1;i>0;i--){const j=(seed*7+i*3+q.q.length)% (i+1);[rows[i],rows[j]]=[rows[j],rows[i]]}return{...q,options:rows.map(x=>x.o),answer:rows.findIndex(x=>x.ok)}}
function profile(u){
 const a=u.examples[0],b=u.examples[1],c=u.examples[2];
 const base={
  goal:`Use ${u.title} accurately when speaking and writing.`,
  why:`This grammar helps you communicate ${u.focus} clearly.`,
  rule:`Study the pattern in the examples. Notice which words change and which words stay in the same position.`,
  decision:`Ask yourself: “What meaning do I need?” Then choose the form that matches ${u.focus}.`,
  pronunciation:`Read the complete sentence in groups of meaning, not word by word. Stress the key information.`,
  mistake1:`Do not mix the structure with a different tense or pattern.`,
  fix1:`Keep the model form: ${a}`,
  prompts:[`Create a true sentence about your life.`,`Ask a classmate one question using this grammar.`,`Change the model sentence to include a different person, place or time.`],
  transform:`Change the subject or time expression without changing the grammar pattern.`
 };
 const custom={
 'Verb to be':{goal:'Introduce yourself and describe people, places and feelings.',why:'Use am, is and are to connect the subject with information about identity, condition or location.',rule:'I + am · He/She/It + is · You/We/They + are. For negatives, add not. For questions, move am/is/are before the subject.',decision:'Choose am for I, is for one person or thing, and are for you or more than one person.',pronunciation:'In natural speech, contractions are common: I’m, you’re, he’s, she’s, we’re, they’re.',mistake1:'Do not use am, is or are with the wrong subject.',fix1:'I am ready. She is ready. They are ready.',prompts:['Say your name, nationality and occupation.','Describe how you feel today.','Ask a partner where they are from.'],transform:'Turn an affirmative sentence into a negative and then into a question.'},
 'Present Simple':{goal:'Talk about routines, repeated actions, facts and permanent situations.',why:'Use the Present Simple when an action happens regularly or is generally true.',rule:'I/You/We/They + base verb. He/She/It + verb-s. Use do/does for questions and do not/does not for negatives.',decision:'Use it for every day, usually, often, never and facts—not for an action happening right now.',pronunciation:'The third-person ending has three sounds: /s/ works, /z/ plays, /ɪz/ watches.',mistake1:'After does or doesn’t, use the base verb without -s.',fix1:'Does she work here? She doesn’t work here.',prompts:['Describe your weekday routine.','Ask three questions about a classmate’s habits.','State two facts about your city.'],transform:'Change “She studies at night” into a negative and a question.'},
 'Present Continuous':{goal:'Describe actions happening now or around the present moment.',why:'Use am/is/are + verb-ing for temporary actions in progress.',rule:'Subject + am/is/are + verb-ing. Put not after am/is/are for negatives. Move am/is/are before the subject for questions.',decision:'Look for now, right now, at the moment or a temporary situation.',pronunciation:'In contractions, is and are become ’s and ’re: she’s working, they’re studying.',mistake1:'Do not omit the verb be before the -ing form.',fix1:'She is working—not “She working”.',prompts:['Say what three people are doing now.','Describe what is happening around you.','Ask a partner what they are working on.'],transform:'Change an affirmative sentence into a question using inversion.'},
 'Present Perfect':{goal:'Connect past experiences or actions with the present.',why:'Use have/has + past participle when the exact finished time is not the main focus.',rule:'I/You/We/They + have + past participle. He/She/It + has + past participle.',decision:'Use it for life experience, recent results and unfinished time periods. Do not combine it with a finished time such as yesterday.',pronunciation:'Have and has are often reduced in speech: I’ve, you’ve, he’s, she’s.',mistake1:'Do not use the Past Simple form after have or has.',fix1:'She has gone—not “She has went”.',prompts:['Name three things you have done this year.','Ask someone about travel experiences.','Describe a recent result you can see now.'],transform:'Replace a finished past time with an unfinished-time expression.'},
 'Articles':{goal:'Choose a, an or the when naming people, places and things.',why:'Articles show whether a noun is general, mentioned for the first time or already identified.',rule:'Use a before a consonant sound, an before a vowel sound, and the for something specific or already known.',decision:'Listen to the first sound, not only the first letter: an hour, a university.',pronunciation:'The is usually /ðə/ before a consonant sound and /ðiː/ before a vowel sound for emphasis or ease.',mistake1:'Do not use a or an with plural nouns.',fix1:'a book · an apple · the books on the table',prompts:['Name five objects around you with articles.','Describe a place and then refer to it again with the.','Find one word that begins with a vowel letter but takes a.'],transform:'Decide whether each noun is new, general or specific.'},
 'Past Simple: regular verbs':{goal:'Describe completed actions at a finished time in the past.',why:'Use the Past Simple for events that started and ended before now.',rule:'Affirmative: verb-ed. Negative: did not + base verb. Question: Did + subject + base verb?',decision:'Use it with yesterday, last week, in 2020 and ago.',pronunciation:'The -ed ending sounds /t/ in worked, /d/ in played and /ɪd/ in wanted.',mistake1:'After did or didn’t, use the base verb.',fix1:'Did she work? She didn’t work.',prompts:['Describe yesterday in five sentences.','Ask a partner what they did last weekend.','Tell a short story with a clear beginning and ending.'],transform:'Turn a regular past affirmative into a negative and question.'},
 'First Conditional':{goal:'Talk about a real and possible future result.',why:'Use it when one future event depends on a realistic condition.',rule:'If + Present Simple, will + base verb. The clauses can change order; use a comma when the if-clause comes first.',decision:'Choose the First Conditional when the condition is possible, not imaginary.',pronunciation:'Pause lightly between the condition and result when the if-clause comes first.',mistake1:'Do not normally use will directly after if.',fix1:'If it rains, we will stay home.',prompts:['Give advice about studying with if.','Predict what you will do if the weather changes.','Ask a partner what they will do if they have free time.'],transform:'Swap the order of the two clauses without changing the meaning.'},
 'Second Conditional':{goal:'Imagine unlikely or unreal present and future situations.',why:'Use it for dreams, hypothetical choices and improbable results.',rule:'If + Past Simple, would + base verb. Were is common for all subjects in formal hypothetical statements.',decision:'Choose it when the situation is imaginary or unlikely now.',pronunciation:'Would is often contracted to ’d: I’d travel, she’d buy.',mistake1:'Do not use would in the if-clause.',fix1:'If I had more time, I would study French.',prompts:['Say what you would do with a million dollars.','Ask a partner about an imaginary trip.','Give a hypothetical solution to a problem.'],transform:'Change a real statement into an imaginary condition.'},
 'Third Conditional':{goal:'Imagine a different result for a past situation that cannot change.',why:'Use it to discuss regrets, missed opportunities and alternative past results.',rule:'If + had + past participle, would have + past participle.',decision:'Both the condition and result refer to an unreal past.',pronunciation:'Would have is often pronounced “would’ve”; had may contract to ’d.',mistake1:'Do not use would have inside the if-clause.',fix1:'If I had known, I would have called.',prompts:['Describe one past decision you would change.','Explain an alternative result in a historical event.','Ask what someone would have done differently.'],transform:'Build a condition from a real past cause and result.'}
 };
 return {...base,...(custom[u.title]||{})};
}
function derivedQuiz(u){
 const p=profile(u),[a,b,c]=u.examples;
 const qs=[
 ...u.quiz.map((q,i)=>shuffledQuestion(q,u.number+i)),
 shuffledQuestion({q:`What is the main communicative goal of ${u.title}?`,options:[p.goal,'Memorize unrelated vocabulary.','Practice only spelling.'],answer:0},u.number+11),
 shuffledQuestion({q:'Which sentence is a model from this lesson?',options:[b,'She do not works every day.','Does he is ready?'],answer:0},u.number+12),
 shuffledQuestion({q:'Which study strategy is best?',options:['Notice the meaning and the complete pattern.','Translate every word separately.','Ignore the subject of the sentence.'],answer:0},u.number+13),
 shuffledQuestion({q:`Which phrase best describes the focus?`,options:[u.focus,'alphabet pronunciation only','unrelated idioms'],answer:0},u.number+14),
 shuffledQuestion({q:'Choose another correct model sentence.',options:[c,'He can to working.','I am go yesterday.'],answer:0},u.number+15)
 ]; return qs.slice(0,10);
}
function lessonPages(u){const p=profile(u),[a,b,c]=u.examples,qz=derivedQuiz(u);return[
{chapter:'Start',title:u.title,html:`<div class="page-inner cover"><span class="unit-label">UNIT ${u.number} · ${u.level}</span><div class="cover-icon">📘</div><h1>${esc(u.title)}</h1><p>${esc(u.focus)}</p><div class="cover-goal">${esc(p.goal)}</div><button class="listen-btn" data-speak="${esc(a)}">🔊 Hear a model sentence</button></div>`},
{chapter:'Goal',title:'Your mission',html:`<div class="page-inner"><span class="page-tag">LEARNING GOAL</span><h2>What will you be able to do?</h2><p class="lead">${esc(p.goal)}</p><div class="mission-list"><div>✓ Understand the meaning</div><div>✓ Build the form</div><div>✓ Use it in real communication</div><div>✓ Avoid the most common error</div></div></div>`},
{chapter:'Notice',title:'Grammar in context',html:`<div class="page-inner"><span class="page-tag">NOTICE</span><h2>Read before studying the rule</h2><div class="story-card"><p>${esc(a)}</p><p>${esc(b)}</p><p>${esc(c)}</p></div><button class="listen-btn" data-speak="${esc([a,b,c].join(' '))}">🔊 Listen to the examples</button><p class="translation">¿Qué palabras cambian? ¿Qué significado comparten las oraciones?</p></div>`},
{chapter:'Meaning',title:'When do we use it?',html:`<div class="page-inner"><span class="page-tag">MEANING</span><h2>${esc(p.why)}</h2><div class="decision-card"><b>Meaning first</b><p>${esc(p.decision)}</p></div><div class="example highlighted">${esc(a)}</div></div>`},
{chapter:'Form',title:'Build the structure',html:`<div class="page-inner"><span class="page-tag">FORM</span><h2>How is it formed?</h2><div class="rule-box large">${esc(p.rule)}</div><div class="sentence-parts"><span>SUBJECT</span><b>+</b><span>GRAMMAR FORM</span><b>+</b><span>INFORMATION</span></div><p class="translation">Usa los ejemplos como modelo. No memorices palabras aisladas.</p></div>`},
{chapter:'Choice',title:'Choose the right form',html:`<div class="page-inner"><span class="page-tag">DECISION GUIDE</span><h2>Stop and ask</h2><div class="choice-steps"><div><strong>1</strong><p>What time or situation am I describing?</p></div><div><strong>2</strong><p>What meaning do I need?</p></div><div><strong>3</strong><p>Which subject and verb form match?</p></div></div><div class="rule-box">${esc(p.decision)}</div></div>`},
{chapter:'Sound',title:'Pronunciation focus',html:`<div class="page-inner"><span class="page-tag">PRONUNCIATION</span><h2>Make it sound natural</h2><p class="lead">${esc(p.pronunciation)}</p><div class="example">${esc(b)}</div><button class="listen-btn" data-speak="${esc(b)}">🔊 Listen and repeat</button><div class="tip-card">Read it once slowly, then once at natural speed.</div></div>`},
{chapter:'Accuracy',title:'Common mistake',html:`<div class="page-inner"><span class="page-tag">COMMON MISTAKE</span><h2>Check before you continue</h2><div class="mistake"><div class="wrong">✗ ${esc(p.mistake1)}</div><div class="correct">✓ ${esc(p.fix1)}</div></div><div class="example">Correct model: ${esc(c)}</div></div>`},
{chapter:'Practice',title:'Guided practice',html:`<div class="page-inner"><span class="page-tag">PRACTICE 1</span><h2>${esc(qz[0].q)}</h2><div class="answer-grid" data-answer="${qz[0].answer}">${qz[0].options.map((x,i)=>`<button class="answer-btn" data-v="${i}">${String.fromCharCode(65+i)}. ${esc(x)}</button>`).join('')}</div><div class="feedback"></div></div>`},
{chapter:'Transform',title:'Change the sentence',html:`<div class="page-inner"><span class="page-tag">PRACTICE 2</span><h2>Transform the model</h2><div class="example">${esc(a)}</div><p class="lead">${esc(p.transform)}</p><textarea class="writing-box" id="transformWriting" placeholder="Write the transformed sentence..."></textarea><button class="mini-btn" id="saveTransform">Save answer</button><div class="feedback" id="transformFeedback"></div></div>`},
{chapter:'Communicate',title:'Use English',html:`<div class="page-inner"><span class="page-tag">SPEAKING & WRITING</span><h2>Make it personal</h2><div class="prompt-list">${p.prompts.map((x,i)=>`<div><strong>${i+1}</strong><span>${esc(x)}</span></div>`).join('')}</div><textarea class="writing-box" id="unitWriting" placeholder="Write your response here..."></textarea><button class="mini-btn" id="saveWriting">Save response</button><div class="feedback" id="writingFeedback"></div></div>`},
{chapter:'Review',title:'One-minute review',html:`<div class="page-inner"><span class="page-tag">REVIEW</span><h2>Before the test</h2><div class="review-grid"><div><small>USE</small><p>${esc(p.why)}</p></div><div><small>FORM</small><p>${esc(p.rule)}</p></div><div><small>MODEL</small><p>${esc(a)}</p></div><div><small>AVOID</small><p>${esc(p.mistake1)}</p></div></div></div>`},
{chapter:'Test',title:'Final test',html:`<div class="page-inner test-page"><span class="page-tag">UNIT TEST</span><h2>10-question evaluation</h2><p class="translation">Necesitas 70% para completar la unidad.</p><div id="lessonQuiz">${qz.map((q,qi)=>`<div class="quiz-block"><b>${qi+1}. ${esc(q.q)}</b>${q.options.map((o,oi)=>`<label><input type="radio" name="lq${qi}" value="${oi}"> ${esc(o)}</label>`).join('')}</div>`).join('')}</div><button class="primary-btn compact" id="gradeLesson">Grade test</button><div class="feedback" id="lessonResult"></div></div>`},
{chapter:'Complete',title:'Lesson result',html:`<div class="page-inner center"><span class="page-tag">COMPLETE</span><div class="big-emoji">🏆</div><h2>${esc(u.title)}</h2><p class="lead">Pass the test with 70% to unlock completion.</p><div class="rule-box">Key model:<br>${esc(a)}</div><button class="primary-btn" id="completeUnit">Complete unit</button><div class="feedback" id="completeFeedback"></div></div>`}
]}
function progress(){const done=Object.keys(state.completed).length,total=D.units.length,p=Math.round(done/total*100);$('#overallPercent').textContent=p+'%';$('#overallBar').style.width=p+'%';$('#overallText').textContent=`${done} de ${total} unidades completadas`;$('#xpText').textContent=state.xp+' XP'}
function renderCatalog(){const box=$('#courseIndex'),q=$('#searchUnits').value.trim().toLowerCase();box.innerHTML='';D.levels.forEach(level=>{if(activeLevel!=='ALL'&&activeLevel!==level)return;const info=D.levelInfo[level],items=D.units.filter(u=>u.level===level&&(!q||(u.title+' '+u.focus).toLowerCase().includes(q)));if(!items.length)return;const sec=document.createElement('section');sec.className='level-section';sec.innerHTML=`<div class="level-heading"><div><span class="level-badge">${level}</span><h2>${info[0]}</h2><p>${info[1]}</p></div><button class="exam-button" data-exam="${level}">📝 Examen ${level}</button></div><div class="unit-grid">${items.map(u=>`<button class="unit-card ${state.completed[u.id]?'done':''}" data-unit="${u.id}"><span class="unit-number">${String(u.number).padStart(2,'0')}</span><div><small>${u.level} · GRAMMAR</small><h3>${u.title}</h3><p>${u.focus}</p></div><span class="unit-status">${state.completed[u.id]?'✓':'→'}</span></button>`).join('')}</div>`;box.appendChild(sec)});box.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.unit));box.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>openExam(b.dataset.exam));progress()}
function openUnit(id){currentUnit=D.units.find(x=>x.id===id);pages=lessonPages(currentUnit);pageIndex=0;$('#catalogView').classList.add('hidden');$('#examView').classList.add('hidden');$('#bookView').classList.remove('hidden');$('#sideUnitTitle').textContent=currentUnit.title;buildNav();renderPage()}
function pageHTML(i){return i>=0&&i<pages.length?pages[i].html:'<div class="page-inner center"><div class="big-emoji">📖</div></div>'}
function isMobileReader(){return matchMedia('(max-width:900px)').matches}
function renderPage(){const mobile=isMobileReader();pageIndex=Math.max(0,Math.min(pageIndex,pages.length-1));if(!mobile&&pageIndex%2!==0)pageIndex--;if(mobile){$('#leftPage').innerHTML='';$('#rightPage').innerHTML=pageHTML(pageIndex)}else{const li=pageIndex%2===0?pageIndex:pageIndex-1;$('#leftPage').innerHTML=pageHTML(li);$('#rightPage').innerHTML=pageHTML(li+1)}const p=pages[pageIndex];$('#pageChapter').textContent=p.chapter.toUpperCase();$('#pageTitleTop').textContent=p.title;$('#pageCurrent').textContent=pageIndex+1;$('#pageTotal').textContent=pages.length;$('#prevBtn').disabled=pageIndex===0;$('#nextBtn').textContent=pageIndex===pages.length-1?'Finish ✓':'Next →';$('#sideProgressBar').style.width=((pageIndex+1)/pages.length*100)+'%';document.querySelectorAll('.chapter-btn').forEach((b,i)=>b.classList.toggle('active',i===pageIndex));bindPage()}
function buildNav(){$('#chapterList').innerHTML=pages.map((p,i)=>`<button class="chapter-btn" data-p="${i}">${String(i+1).padStart(2,'0')} · ${p.title}</button>`).join('');$('#chapterList').querySelectorAll('button').forEach(b=>b.onclick=()=>{pageIndex=+b.dataset.p;renderPage();$('#sidebar').classList.remove('open')});$('#pageDots').innerHTML=pages.map(()=>'<span class="dot"></span>').join('')}
function bindPage(){document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));document.querySelectorAll('.answer-grid').forEach(g=>g.querySelectorAll('button').forEach(b=>b.onclick=()=>{g.querySelectorAll('button').forEach(x=>x.disabled=true);const ok=+b.dataset.v===+g.dataset.answer;b.classList.add(ok?'correct':'wrong');const f=g.nextElementSibling;f.textContent=ok?'✓ Correct!':'Not yet. Review the meaning and model sentence.';f.style.color=ok?'var(--success)':'var(--danger)'}));const bindSave=(btnId,boxId,feedbackId,key)=>{const btn=$(btnId);if(btn)btn.onclick=()=>{state.answers[currentUnit.id+key]=$(boxId).value;save();$(feedbackId).textContent='✓ Saved'}};bindSave('#saveWriting','#unitWriting','#writingFeedback','-writing');bindSave('#saveTransform','#transformWriting','#transformFeedback','-transform');const grade=$('#gradeLesson');if(grade)grade.onclick=()=>{const qz=derivedQuiz(currentUnit);let s=0;qz.forEach((q,i)=>{const c=document.querySelector(`input[name=lq${i}]:checked`);if(c&&+c.value===q.answer)s++});const pct=Math.round(s/qz.length*100),r=$('#lessonResult');r.textContent=`Score: ${s}/${qz.length} (${pct}%) — ${pct>=70?'Passed!':'Review the lesson and try again.'}`;r.style.color=pct>=70?'var(--success)':'var(--danger)';state.answers[currentUnit.id+'-test']=pct;save();if(pct>=70)toast('Unit test passed ✓')};const complete=$('#completeUnit');if(complete)complete.onclick=()=>{const pct=state.answers[currentUnit.id+'-test']||0;if(pct<70){$('#completeFeedback').textContent='Complete the test with at least 70% first.';return}if(!state.completed[currentUnit.id]){state.completed[currentUnit.id]=true;state.xp+=100;save();toast('+100 XP · Unit completed')}backCatalog()}}
function backCatalog(){$('#bookView').classList.add('hidden');$('#examView').classList.add('hidden');$('#catalogView').classList.remove('hidden');renderCatalog()}
function openExam(level){const us=D.units.filter(u=>u.level===level),pool=[];us.forEach(u=>pool.push(...derivedQuiz(u).slice(0,2).map(q=>({...q,unit:u.title}))));const exam=pool.slice(0,30);$('#catalogView').classList.add('hidden');$('#bookView').classList.add('hidden');$('#examView').classList.remove('hidden');$('#examLevelLabel').textContent=`LEVEL ${level}`;$('#examTitle').textContent=`Evaluación acumulativa ${level}`;$('#examIntro').textContent=`${exam.length} preguntas variadas sobre las unidades del nivel. Necesitas 70% para aprobar.`;$('#examQuestions').innerHTML=exam.map((q,i)=>`<div class="exam-question"><span>${i+1}</span><div><b>${esc(q.q)}</b><small>${esc(q.unit)}</small>${q.options.map((o,j)=>`<label><input type="radio" name="eq${i}" value="${j}"> ${esc(o)}</label>`).join('')}</div></div>`).join('');$('#examResult').innerHTML='';$('#submitExam').onclick=()=>{let s=0;exam.forEach((q,i)=>{const c=document.querySelector(`input[name=eq${i}]:checked`);if(c&&+c.value===q.answer)s++});const p=Math.round(s/exam.length*100),pass=p>=70;$('#examResult').innerHTML=`<strong>${p}%</strong><p>${s} de ${exam.length} respuestas correctas.</p><b>${pass?'✓ Nivel aprobado':'Repasa las unidades e inténtalo nuevamente.'}</b>`;if(pass&&!state.exams[level]){state.exams[level]=p;state.xp+=250;save();progress();toast('+250 XP · Level passed')}}}
$('#levelFilters').innerHTML=['ALL',...D.levels].map(x=>`<button data-level="${x}" class="${x==='ALL'?'active':''}">${x==='ALL'?'Todos':x}</button>`).join('');$('#levelFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeLevel=b.dataset.level;document.querySelectorAll('#levelFilters button').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$('#searchUnits').oninput=renderCatalog;$('#soundToggle').onclick=()=>{soundOn=!soundOn;$('#soundToggle').textContent=soundOn?'🔊':'🔇'};$('#backCatalog').onclick=backCatalog;$('#backFromExam').onclick=backCatalog;$('#brandHome').onclick=backCatalog;$('#openSidebar').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');$('#prevBtn').onclick=()=>{pageIndex-=isMobileReader()?1:2;renderPage()};$('#nextBtn').onclick=()=>{const step=isMobileReader()?1:2;if(pageIndex+step<pages.length){pageIndex+=step;renderPage()}else if(pageIndex<pages.length-1){pageIndex=pages.length-1;renderPage()}else backCatalog()};addEventListener('resize',()=>{if(currentUnit&&!$('#bookView').classList.contains('hidden'))renderPage()});document.addEventListener('keydown',e=>{if($('#bookView').classList.contains('hidden'))return;if(e.key==='ArrowRight')$('#nextBtn').click();if(e.key==='ArrowLeft')$('#prevBtn').click()});renderCatalog();
})();
